name:                generic-persistence-demo
version:             0.1.0.0
github:              "thma/generic-persistence-demo"
license:             BSD3
author:              "Thomas Mahler"
maintainer:          "thma@apache.org"
copyright:           "2023 Thomas Mahler"
language:            GHC2021 

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Some small demos for the generic-persistence library
category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thma/generic-persistence-demo#readme>

dependencies:
- base >= 4.7 && < 5
- generic-persistence
- HDBC-sqlite3
- HDBC

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


executables:
  generic-persistence-demo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
